version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/app/assets
    build:
        context: .
    expose:
      - 8000
    env_file:
      - .env.dev
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cloudproject
      - POSTGRES_USER=clouduser
      - POSTGRES_PASSWORD=password
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
    - 1337:80
    depends_on:
    - django_gunicorn

volumes:
    postgres_data:
    static:
